apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: project-secrets
  namespace: demo
spec:
  encryptedData:
    ENCRYPT_KEY: AgCT/cY7R6qEQHjrlNEtD+iRBJ3y5qyPtUzYSvpMTl/UOaRwPIMJLIcsbAh+zlL5SRktkYLgLP4Zv9y6OaYiMP+bDnEJW2fKod8+y7xxx0n32NR+VjEWSwn46lPlhprJTe9UlRikfaLR1ztSMGN0Zq/uU2bAAK2qnyuKHku60F/UpYvDV3idvpCoS9Ch3VvZCtTbOsr2i7PfHKcAfL92jB1Rkw2ovfK4oH8TRPA4mz6RBBiPq3ZP8tTIwDJNEpDmqYGlcz74hSOzIKbNA7SrPmh24rwg44KxFoD5WUHTvVMP/3aPSzFrR43bZgnaGLE4ly8k3ghxUEMPWPauwhIMU71cUGMfnubqauO0YFVG3FL5MgyrAjag5MR0iiTib/vXw9qh9s9CBO6I7A+Qxetdg4lWRMYfn8+X117+rwn63EURooQihPh6XKuBdZv4JLiQ9cn0uDX4eflAlMCwUh0jC2Xfnuw4nunSSuqorHuFYaiEDLVVlbZ3AB1G57DWHEC3MVGiGiOMOwZTnb8+lgJqMdPXIDoGkz7E9u4azF+ueaj2XuGaf5yEy600Pn+1mKV+V8IgHtzZ0exRcN9/ky5kbeAKARLeETKUBujbxD4VLbW5zaYWozwZzdQizsGijJNZmgGClAcHwK0VNwnqnPTUe0famhMzsxxnqsvTWt8Z8LvnkUjw0AmltfLw+WRrswHjDNrn2dXQN5CMD3y5egxQdRHLQCLiOL8JcNg3Z/X1TGf0zseTTvI=
    SPRING_DATA_MONGODB_URI: AgAoNcypZgi9+5k7KBwAj5117IPYoLSvdpIlTcGqVW6uBZKR9emgLbqfqDWe1aEeZ8QIwAAIeotO9sk/hWvEMhnAJaVTvj/kYR+QklXb3kE0FQRX+3bjsck+xqWQPiBVrnE5lnRIcnIobnb5M6uU08NogHorCrA3RZEQPYa58824v9Mp7qKEA9MhJY46li3f7JwT+A7KETFiTifZTkENhL1KqUuBnB16QbSydpHaOhSLCDi2JVrYbjb7HFIt+256+4gQhP4S16AuCw30XYohKNx8SoCfFkk7xsMQaitz9sTgdLj2RHO5cZXycCPfesXF6kL4aJJPQAvLOlVBCnkbhkWY1NMdP4PuJem66Li7fVR17BNp+BfYczhNhVZAyrT/zHePn2ohb3GNBluzIJ5uS/V9NP1V0KvwEwz3sZyyLNCr8nzTvQlCTkEUsc54hCLLm/x9ieEcrsOfoFwsOICcfGhSbh7+MpcyURQyhyFskcSgXeSOvCh1vfAkZGhKroxrYq4Nc4jbpmRbfmthF6WB9sVdf/ikZyzy8xXsw0+zupxxe8T6gIZ/J08X+OHwUelgbD8UjrM2FxcOHkNY+oAQfidwF0awFohgN/PfiIIxbDhP0Nm97FQE90d9im5TM/lyM/F5qQJtoL3eQnBDfP0QTO3gNvHssvr7J3pKkWW+0SkFPcAo/9aVyiXkv5PLSKJ4eTkwgsL/zmpI51124TBE9aXL7Z++nGrysZGBOAj6L2X/jwNF8BqVJ3+ktsVJuOQ5xqMuC20dGEDmmeC3IOF0LINcUQ1rMclH8zPJVPTW16vJW0lAiU+FqTQG/5YrjmdEh666k1S+bdXXRODWvxLh1hZh/V0d7xk1ipYS9LbXtC94aiVb2fEHvrt5FaG8k4ZcoqaGqvBXyYXJmnkqwnyOd7Y2xHRnQbAS31y6xOzeaTGh4uvg0Xf+5SDZWxtgCIR0sYscEiXZoq+EcwGMhyWNZXDZaaCnjQmyX658FjBUJ58=
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: project-secrets
      namespace: demo

