#common configuration shared between all applications
configserver:
  name: Docker JHipster Registry
  status: Connected to the JHipster Registry running in Docker

jhipster:
  security:
    authentication:
      jwt:
        base64-secret: ODQyMjkwMWFkMGMwMTE3NDVmMzcyMDBkYzdmZmQ4NTk0YjliOWU4NzNiNmVkNGViMzM5YmFjMTgxNDhmNTc2MTg1NDUxODFhNmI3ZWEzZmY1M2M4ODY0MDBiODUxMGMyYjViMw==
eureka:
  client:
    service-url:
      defaultZone: http://admin:${jhipster.registry.password}@jhipster-registry:8761/eureka/

spring:
  security:
    oauth2:
      client:
        provider:
          oidc:
            issuer-uri: https://dev-447850.okta.com/oauth2/default
        registration:
          oidc:
            client-id: 0oa6ycmlneJOs6wNC4x7
            client-secret: "{cipher}88acb434dd065110f2463574b13895e09d04f78ffee2f55a0effcbcd6355d437d813dbd34ec6521fa86ee9573f468d6c59c43b2a435d1ea6e93bc01089928acb"
