apiVersion: v1
kind: ConfigMap
metadata:
  name: application-config
  namespace: demo
#common configuration shared between all applications
data:
  application.yml: |-
    configserver:
      name:  JHipster Registry
      status: Connected to the JHipster Registry running in Kubernetes
    eureka:
      client:
        initial-instance-info-replication-interval-seconds: 15
        instance-info-replication-interval-seconds: 15
        registry-fetch-interval-seconds: 15
        fetch-registry: true
        register-with-eureka: true
        eureka-service-url-poll-interval-seconds: 15
      instance:
        lease-renewal-interval-in-seconds: 10
        registry-default-open-for-traffic-count: 0
    jhipster:
      security:
        authentication:
          jwt:
            base64-secret: MGYyOWI2ZGQxMjZmNmVkNmZlNjNlN2E0ZjQyOGNmYjViMGJlNzRjODJlZTlkOTkzM2E5YjEzOTA2NDE3ZmNmZDRkNGMzMDI3ZGE2ZDA5ZGY4YTMzOGYwZDg4OGRhODc1NDgzOA==
    spring:
      security:
        oauth2:
          client:
            provider:
              oidc:
                issuer-uri: https://dev-447850.okta.com/oauth2/default
            registration:
              oidc:
                client-id: 0oa6ycmlneJOs6wNC4x7
                client-secret: "{cipher}786174c9090895feda62650f9c768a3ea6b9d52cd49dffff95c27a7712572a1ff2c8fd7b4a7bbd201c84999f8dcd10925da635e5151c65be768ea2c9699b2c28"

  # app specific configuration
  jhipster-registry.yml: |-
    eureka:
      client:
        service-url:
          defaultZone: http://admin:${spring.security.user.password}@jhipster-registry-0.jhipster-registry.demo.svc.cluster.local:8761/eureka/,http://admin:${spring.security.user.password}@jhipster-registry-1.jhipster-registry.demo.svc.cluster.local:8761/eureka/
